openapi: 3.0.3
info:
  title: Familienkasse API
  description: API for managing family finance accounts and transactions
  version: 1.0.0

servers:
  - url: /api
    description: Local API

paths:
  /accounts:
    get:
      summary: List all accounts for authenticated user
      operationId: listAccounts
      tags: [Accounts]
      security:
        - session: []
      responses:
        '200':
          description: List of accounts with balances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountWithBalance'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create a new account
      operationId: createAccount
      tags: [Accounts]
      security:
        - session: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /accounts/{accountId}:
    parameters:
      - $ref: '#/components/parameters/AccountId'

    get:
      summary: Get account details with balance
      operationId: getAccount
      tags: [Accounts]
      security:
        - session: []
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountWithBalance'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update account name
      operationId: updateAccount
      tags: [Accounts]
      security:
        - session: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccountRequest'
      responses:
        '200':
          description: Account updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete account and all its transactions
      operationId: deleteAccount
      tags: [Accounts]
      security:
        - session: []
      responses:
        '204':
          description: Account deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /accounts/{accountId}/transactions:
    parameters:
      - $ref: '#/components/parameters/AccountId'

    get:
      summary: List transactions for an account
      operationId: listTransactions
      tags: [Transactions]
      security:
        - session: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  total:
                    type: integer
                    description: Total count of transactions
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Create a new transaction
      operationId: createTransaction
      tags: [Transactions]
      security:
        - session: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequest'
      responses:
        '201':
          description: Transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /accounts/{accountId}/transactions/{transactionId}:
    parameters:
      - $ref: '#/components/parameters/AccountId'
      - $ref: '#/components/parameters/TransactionId'

    get:
      summary: Get transaction details
      operationId: getTransaction
      tags: [Transactions]
      security:
        - session: []
      responses:
        '200':
          description: Transaction details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update transaction
      operationId: updateTransaction
      tags: [Transactions]
      security:
        - session: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransactionRequest'
      responses:
        '200':
          description: Transaction updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete transaction
      operationId: deleteTransaction
      tags: [Transactions]
      security:
        - session: []
      responses:
        '204':
          description: Transaction deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    session:
      type: apiKey
      in: cookie
      name: better-auth.session_token
      description: Better-Auth session cookie

  parameters:
    AccountId:
      name: accountId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Account ID

    TransactionId:
      name: transactionId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Transaction ID

  schemas:
    Account:
      type: object
      required: [id, name, userId, createdAt, updatedAt]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
        userId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    AccountWithBalance:
      allOf:
        - $ref: '#/components/schemas/Account'
        - type: object
          required: [balance]
          properties:
            balance:
              type: integer
              description: Balance in cents

    CreateAccountRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100

    UpdateAccountRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100

    Transaction:
      type: object
      required: [id, accountId, amount, isPaid, createdAt]
      properties:
        id:
          type: string
          format: uuid
        accountId:
          type: string
          format: uuid
        description:
          type: string
          maxLength: 500
          nullable: true
        amount:
          type: integer
          description: Amount in cents (positive = deposit, negative = withdrawal)
        isPaid:
          type: boolean
          description: Whether this transaction has been fulfilled
        createdAt:
          type: string
          format: date-time

    CreateTransactionRequest:
      type: object
      required: [amount]
      properties:
        description:
          type: string
          maxLength: 500
        amount:
          type: integer
          description: Amount in cents
        isPaid:
          type: boolean
          default: false

    UpdateTransactionRequest:
      type: object
      properties:
        description:
          type: string
          maxLength: 500
        amount:
          type: integer
        isPaid:
          type: boolean

    Error:
      type: object
      required: [message]
      properties:
        message:
          type: string
        code:
          type: string

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
