/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts/$accountId'
import { Route as ApiAccountsIndexRouteImport } from './routes/api/accounts/index'
import { Route as ApiCronWeeklyAllowanceRouteImport } from './routes/api/cron/weekly-allowance'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAccountsAccountIdIndexRouteImport } from './routes/api/accounts/$accountId/index'
import { Route as ApiAccountsAccountIdTransactionsIndexRouteImport } from './routes/api/accounts/$accountId/transactions/index'
import { Route as ApiAccountsAccountIdTransactionsTransactionIdRouteImport } from './routes/api/accounts/$accountId/transactions/$transactionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsIndexRoute = ApiAccountsIndexRouteImport.update({
  id: '/api/accounts/',
  path: '/api/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWeeklyAllowanceRoute = ApiCronWeeklyAllowanceRouteImport.update({
  id: '/api/cron/weekly-allowance',
  path: '/api/cron/weekly-allowance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsAccountIdIndexRoute =
  ApiAccountsAccountIdIndexRouteImport.update({
    id: '/api/accounts/$accountId/',
    path: '/api/accounts/$accountId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountsAccountIdTransactionsIndexRoute =
  ApiAccountsAccountIdTransactionsIndexRouteImport.update({
    id: '/api/accounts/$accountId/transactions/',
    path: '/api/accounts/$accountId/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountsAccountIdTransactionsTransactionIdRoute =
  ApiAccountsAccountIdTransactionsTransactionIdRouteImport.update({
    id: '/api/accounts/$accountId/transactions/$transactionId',
    path: '/api/accounts/$accountId/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-allowance': typeof ApiCronWeeklyAllowanceRoute
  '/api/accounts/': typeof ApiAccountsIndexRoute
  '/api/accounts/$accountId/': typeof ApiAccountsAccountIdIndexRoute
  '/api/accounts/$accountId/transactions/$transactionId': typeof ApiAccountsAccountIdTransactionsTransactionIdRoute
  '/api/accounts/$accountId/transactions/': typeof ApiAccountsAccountIdTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-allowance': typeof ApiCronWeeklyAllowanceRoute
  '/api/accounts': typeof ApiAccountsIndexRoute
  '/api/accounts/$accountId': typeof ApiAccountsAccountIdIndexRoute
  '/api/accounts/$accountId/transactions/$transactionId': typeof ApiAccountsAccountIdTransactionsTransactionIdRoute
  '/api/accounts/$accountId/transactions': typeof ApiAccountsAccountIdTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-allowance': typeof ApiCronWeeklyAllowanceRoute
  '/api/accounts/': typeof ApiAccountsIndexRoute
  '/api/accounts/$accountId/': typeof ApiAccountsAccountIdIndexRoute
  '/api/accounts/$accountId/transactions/$transactionId': typeof ApiAccountsAccountIdTransactionsTransactionIdRoute
  '/api/accounts/$accountId/transactions/': typeof ApiAccountsAccountIdTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/accounts/$accountId'
    | '/api/config'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/weekly-allowance'
    | '/api/accounts/'
    | '/api/accounts/$accountId/'
    | '/api/accounts/$accountId/transactions/$transactionId'
    | '/api/accounts/$accountId/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/accounts/$accountId'
    | '/api/config'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/weekly-allowance'
    | '/api/accounts'
    | '/api/accounts/$accountId'
    | '/api/accounts/$accountId/transactions/$transactionId'
    | '/api/accounts/$accountId/transactions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/accounts/$accountId'
    | '/api/config'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/weekly-allowance'
    | '/api/accounts/'
    | '/api/accounts/$accountId/'
    | '/api/accounts/$accountId/transactions/$transactionId'
    | '/api/accounts/$accountId/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronWeeklyAllowanceRoute: typeof ApiCronWeeklyAllowanceRoute
  ApiAccountsIndexRoute: typeof ApiAccountsIndexRoute
  ApiAccountsAccountIdIndexRoute: typeof ApiAccountsAccountIdIndexRoute
  ApiAccountsAccountIdTransactionsTransactionIdRoute: typeof ApiAccountsAccountIdTransactionsTransactionIdRoute
  ApiAccountsAccountIdTransactionsIndexRoute: typeof ApiAccountsAccountIdTransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/': {
      id: '/api/accounts/'
      path: '/api/accounts'
      fullPath: '/api/accounts/'
      preLoaderRoute: typeof ApiAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/weekly-allowance': {
      id: '/api/cron/weekly-allowance'
      path: '/api/cron/weekly-allowance'
      fullPath: '/api/cron/weekly-allowance'
      preLoaderRoute: typeof ApiCronWeeklyAllowanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/$accountId/': {
      id: '/api/accounts/$accountId/'
      path: '/api/accounts/$accountId'
      fullPath: '/api/accounts/$accountId/'
      preLoaderRoute: typeof ApiAccountsAccountIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/$accountId/transactions/': {
      id: '/api/accounts/$accountId/transactions/'
      path: '/api/accounts/$accountId/transactions'
      fullPath: '/api/accounts/$accountId/transactions/'
      preLoaderRoute: typeof ApiAccountsAccountIdTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/$accountId/transactions/$transactionId': {
      id: '/api/accounts/$accountId/transactions/$transactionId'
      path: '/api/accounts/$accountId/transactions/$transactionId'
      fullPath: '/api/accounts/$accountId/transactions/$transactionId'
      preLoaderRoute: typeof ApiAccountsAccountIdTransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronWeeklyAllowanceRoute: ApiCronWeeklyAllowanceRoute,
  ApiAccountsIndexRoute: ApiAccountsIndexRoute,
  ApiAccountsAccountIdIndexRoute: ApiAccountsAccountIdIndexRoute,
  ApiAccountsAccountIdTransactionsTransactionIdRoute:
    ApiAccountsAccountIdTransactionsTransactionIdRoute,
  ApiAccountsAccountIdTransactionsIndexRoute:
    ApiAccountsAccountIdTransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
